FROM rayproject/ray:2.6.3-py311-gpu

RUN sudo apt update -y \
    && sudo apt install -y openjdk-8-jdk \
    && sudo apt clean

ENV RAY_memory_monitor_refresh_ms 0

# ray container is NOT Rootless, so must 'pip --user'
RUN $HOME/anaconda3/bin/pip install --no-cache-dir --user pyspark==3.3.2
RUN $HOME/anaconda3/bin/pip install --no-cache-dir --user raydp==1.6.0